# Generated by Django 5.1.7 on 2025-03-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='media_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.media_app'),
        ),
        migrations.AlterField(
            model_name='history',
            name='media_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.media_app'),
        ),
    ]
